# Generated by Django 3.1.7 on 2021-05-29 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 14, 41, 35, 546652)),
        ),
    ]
