# Generated by Django 3.1.7 on 2021-05-29 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Default String', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 14, 43, 36, 436725)),
        ),
    ]
