# Generated by Django 3.1.7 on 2021-05-29 08:45

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210529_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 14, 45, 7, 615168)),
        ),
    ]
