# Generated by Django 3.1.7 on 2021-05-29 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210529_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 17, 34, 56, 671592)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
