# Generated by Django 3.1.7 on 2021-05-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210529_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
