# Generated by Django 3.1.7 on 2021-05-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210530_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='superuser_statue',
            field=models.BooleanField(default=False),
        ),
    ]
