# Generated by Django 3.1.7 on 2021-05-31 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog_superuser_statue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='superuser_statue',
            new_name='superuser_status',
        ),
    ]
