# Generated by Django 3.1.7 on 2021-05-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210531_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='superuser_status',
        ),
    ]
